import { describe, it, expect } from "vitest";
import {
  decodeDuel,
  decodeResult,
  decodeAny,
  previewCopyFor,
  renderPreviewHtml,
  inviteCopyFor,
  renderInviteHtml,
} from "./preview.js";
import vectors from "./duelcode.vectors.json" with { type: "json" };

// Canonical vectors are generated by debug/duel_tracer.py (the app's own
// reference port of DuelCode.swift). Passing these proves ALGORITHM PARITY with
// the shipped Swift encoder — old shared links (C5, FR-30) decode correctly here.

describe("parity with the app's DuelCode encoder (canonical vectors)", () => {
  it("decodes every duel vector to the exact fields", () => {
    for (const v of vectors.duel) {
      const got = decodeDuel(v.code);
      expect(got, v.code).not.toBeNull();
      expect(got!.mode).toBe(v.mode);
      expect(got!.language).toBe(v.language);
      expect(got!.wordIndex).toBe(v.wordIndex);
    }
  });

  it("decodes every result vector to the exact fields", () => {
    for (const v of vectors.result) {
      const got = decodeResult(v.code);
      expect(got, v.code).not.toBeNull();
      expect(got!.language).toBe(v.language);
      expect(got!.wordIndex).toBe(v.wordIndex);
      expect(got!.solved).toBe(v.solved);
      expect(got!.gaveUp).toBe(v.gaveUp);
      expect(got!.guessCount).toBe(v.guessCount);
    }
  });
});

describe("cross-kind & garbage rejection", () => {
  it("a duel code does not decode as a result (and vice versa)", () => {
    const duel = vectors.duel[0]!.code;
    const result = vectors.result[0]!.code;
    expect(decodeResult(duel)).toBeNull();
    expect(decodeDuel(result)).toBeNull();
  });

  it("rejects malformed / empty / foreign strings", () => {
    for (const junk of ["", "WK-", "WR-", "hello", "WK-!!!", "ZZ ZZ", "wk-????"]) {
      expect(decodeDuel(junk)).toBeNull();
      expect(decodeResult(junk)).toBeNull();
    }
  });

  it("prefix is case-insensitive but the base62 body is case-sensitive (matches Swift)", () => {
    const withPrefix = vectors.duel[3]!.code; // e.g. WK-xxxx (original-case body)
    const body = withPrefix.slice(3);
    // Bare body (no prefix) decodes.
    expect(decodeDuel(body)).not.toBeNull();
    // Lowercased PREFIX + original-case body decodes.
    expect(decodeDuel("wk-" + body)).not.toBeNull();
    // Fully lowercased (body mangled) must NOT decode — mirrors DuelCode.swift.
    expect(decodeDuel(withPrefix.toLowerCase())).toBeNull();
  });
});

describe("preview never reveals a word and never 404s (FR-5, FR-30/OD-7)", () => {
  it("garbled codes still yield a friendly generic card", () => {
    const copy = previewCopyFor("totally-not-a-code");
    expect(copy.title).toMatch(/challenged/i);
    expect(copy.description.length).toBeGreaterThan(0);
  });

  it("a legacy race duel code lands gracefully", () => {
    const raceCode = vectors.duel.find((v) => v.mode === "race")!.code;
    const copy = previewCopyFor(raceCode);
    expect(copy.title).toMatch(/Wick/);
  });

  it("result card shows outcome but no word", () => {
    const solved = vectors.result.find((v) => v.solved)!;
    const copy = previewCopyFor(solved.code);
    expect(copy.title.toLowerCase()).toContain("guess");
  });

  it("rendered HTML has OG tags, the app link, escapes, and no secret word", () => {
    const html = renderPreviewHtml({
      code: vectors.duel[0]!.code,
      appLink: "https://jasonepage.github.io/wick/d/" + vectors.duel[0]!.code,
    });
    expect(html).toContain('property="og:title"');
    expect(html).toContain('property="og:description"');
    expect(html).toContain("jasonepage.github.io");
    // decodeAny recovers only an index, never a word — sanity that nothing wordy leaks.
    const decoded = decodeAny(vectors.duel[0]!.code);
    expect(decoded).not.toBeNull();
    expect(JSON.stringify(decoded)).not.toMatch(/word":"/); // wordIndex is a number, not text
  });

  it("escapes HTML in the app link to avoid injection", () => {
    const html = renderPreviewHtml({ code: "WK-abc", appLink: 'https://x/"><script>alert(1)</script>' });
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;");
  });
});

describe("live-invite page (3.1 /p/:code)", () => {
  it("copy is mode-aware and never reveals a word", () => {
    expect(inviteCopyFor("race").title.toLowerCase()).toContain("race");
    expect(inviteCopyFor("dare").title.toLowerCase()).toContain("dared");
    // Generic fallback when no mode is given.
    expect(inviteCopyFor(undefined).title).toMatch(/Wick/);
  });

  it("renders OG tags + a redirect into the web client to play", () => {
    const html = renderInviteHtml({
      code: "AB7QK",
      mode: "race",
      playLink: "/?p=AB7QK&m=race",
      appLink: "https://guesswick.com/p/AB7QK?m=race",
    });
    expect(html).toContain('property="og:title"');
    expect(html).toContain("guesswick.com");
    expect(html).toContain('http-equiv="refresh"');
    expect(html).toContain("location.replace(");
    expect(html).toContain("/?p=AB7QK&amp;m=race"); // play link, HTML-escaped
  });

  it("escapes the play link and can't break out of the <script> redirect", () => {
    const html = renderInviteHtml({
      code: "x",
      mode: "dare",
      playLink: '/?p=</script><script>alert(1)</script>',
      appLink: "https://guesswick.com/p/x?m=dare",
    });
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("\\u003c"); // the redirect literal is neutralised
  });
});
